### ISSUE TITLE
Enable CSRF Validation

### ISSUE THREAD

**Issue by tbreuss** [tbreuss/pingcrm-yii2#1]
Inertia depends on Axios which is refering to the cookie XSRF-TOKEN and the header X-XSRF-TOKEN.

Yii2 is handling CSRF validation different which leads to "Bad Request (#400): Unable to verify your data submission" issues.

**Comment by supersexy** [comment]
Is there any solution for this important issue?

**Comment by tbreuss** [comment]
This demo project is using https://github.com/tbreuss/yii2-inertia under the hood. This is the Yii2 adapter for https://github.com/inertiajs/inertia. So, this issue should be fixed with https://github.com/tbreuss/yii2-inertia/commit/02a6d5e15c1084dbf5d81048ae49ce833518b62c

I will do an update the next days.

**Comment by tbreuss** [comment]
Fixed with c4a2dfaaf60f33b10dbf500ea11ea6942b32ecf8
