### ISSUE TITLE
Demo App is broken

### ISSUE THREAD

**Issue by juppwerner** [tbreuss/pingcrm-yii2#29]
Hello, 

the demo app at https://pingcrm-yii2.tebe.ch/login shows an empty page.

The JavaScript console error is: 

vue.runtime.esm.js:620 
        
       [Vue warn]: Property or method "$page" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Login> at resources/js/Pages/Auth/Login.vue
       <Inertia>
         <Root>#

The same is seen when doing a git clode and npm ci ... , as described in the README.

Thank you.

Kind regards
Jaochim

**Comment by tbreuss** [comment]
Thanks for reporting. I suspect this has to do with the dependabot fix and deployment, which seems to be executed on every commit to the master branch. I'll try to fix this soon.

**Comment by tbreuss** [comment]
Fixed with 755356c3909b9a827c6fb340702a0d2c56f5280a reverting back to the last working version.
